config/routes.rb
Rails.application.routes.draw do
  root to: 'parts#index'

  get '/parts', to: 'parts#list'
  
  get '/parts/search', to: 'parts#search'

  get '/parts/:name(/version/:version)', to: 'parts#show', :version => /.*/

  get '/api/part/:part_name(/version/:version)', to: 'api#getPart', :version => /.*/

  get '/api/part/:part_name/dependency', to: 'api#getPartDependencies'

  post '/api/upload', to: 'api#upload'
  
  post '/api/part/downloaded', to: 'api#incrementDownload'

  get '/api/validateDependencies/:dependencies', :dependencies => /.*/, to: 'api#validateDependencies'

  get '/demo/skeleton', to: 'demo#skeleton'

  get '/demo/social_footer', to: 'demo#social_footer'

  get '/demo/applemenu', to: 'demo#applemenu'

  get '/demo/purecss', to: 'demo#purecss'

  get '/demo/zenlike', to: 'demo#zenlike'

  get '/demo/redtie', to: 'demo#redtie'

  get '/demo/flat_tab_menu', to: 'demo#flat_tab_menu'

end

app/models/Part.rb
class Part < ActiveRecord::Base
end

app/models/part.rb
class Part < ActiveRecord::Base
end

app/controllers/parts_controller.rb
class PartsController < ActionController::Base
	def index
    end

    def list
        @parts = Part.paginate(page: params[:page], per_page: 9).order(name: :asc)
	end

    def getDownloadLink(part, version)
        homepage = part.homepage
        homepage.slice! "https:\/\/github.com\/"
        homepage = homepage.split("\/")
        repo_owner = homepage[0]
        repo_name = homepage[1]
        return "https://api.github.com/repos/#{repo_owner}/#{repo_name}/zipball/#{version}"
    end

    def show
        @part = Part.where(:name => params[:name]).first
        @versions = Version.where(:part_name => @part.name).order(version: :desc)
        @homepage = @part.homepage.clone
        version = params[:version] ? params[:version] : @part.version
        @downloads = @versions.where(:version => version).first.number_of_downloads
        @downloadLink = getDownloadLink(@part, version)
        @dependencies = Dependency.where(:part_version => version, :part_name=> @part.name)
    end

    def search
        @title = 'Search Results'

        if Rails.env.production?
            @parts = Part.paginate(page: params[:page], per_page: 9).where("\"name\" ILIKE \'%#{params[:search]}%\' or \"description\" ILIKE \'%#{params[:search]}%\'")
        else
            @parts = Part.paginate(page: params[:page], per_page: 9).where("name LIKE \"%#{params[:search]}%\" or description LIKE \"%#{params[:search]}%\"").order(name: :asc)
        end
    end
end

app/views/parts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RichCSS Parts</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="homepage">
  <div class="container">
    <div class="row">
      <div class="search">
        <h1 class="homepage-title"> Browse and Download <br> RichCSS. </h1>

        <div class="input-group search-control-container">
          <%= form_tag "/parts/search", :method => 'get', :class => 'search-control' do %>
              <%= text_field_tag :search, params[:search], :class => 'form-control', :placeholder => "Search RichCSS..." %>
              <%= submit_tag "Search", :class => 'search-button', :value=>'⌕' %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="footer">
        <%= link_to "Browse All Parts", parts_path, :class => "color-white" %>
        |
        <%= link_to "RichCSS Documentation", "https://docs.google.com/document/d/1vT3Zpnll7OJV-TLhKijk5KVQdVTiFnUAiuAgoFPVHCM", :class => "color-white" %>
      </div>
    </div>

    <div class="row">
      <div class="install-cli-button">
        <div class="install-cli-button-circle">
          <a href="https://rubygems.org/gems/richcss" class="install-cli-button">
            Install RichCLI
          </a>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="description">
        "RichCSS is a CSS framework providing default structures for reusable css elements. It’s built around an Architectural Style that organizes your code in a way that allows: reusability of your css, versioning, the use of css plugins and the ease of using it. RichCSS is bringing convention and organization to CSS that anyone can understand and use.

        RichCSS is the V2 of ROOCSS. It’s a CSS Framework that makes it easy to organize and use CSS in teams." - Richardson Dackam
      </div>
    </div>
  </div>

  <div class="dev-container">
    <div class="row devs">
      Team
    </div>
    <div class="row devslist">
      <div class="col-md-1">
      </div>
      <div class="col-md-2">
        <%= image_tag "gabriel.jpg", :class => "dev-img" %>
        <div class="dev-name">Gabriel Cheng</div>
      </div>
      <div class="col-md-2">
        <%= image_tag "jon.jpg", :class => "dev-img" %>
        <div class="dev-name">Jonathan Lai</div>
      </div>
      <div class="col-md-2">
        <%= image_tag "nicholas.jpg", :class => "dev-img" %>
        <div class="dev-name">Nicholas Lo</div>
      </div>
      <div class="col-md-2">
        <%= image_tag "bill.jpg", :class => "dev-img" %>
        <div class="dev-name">Bill Xu</div>
      </div>
      <div class="col-md-2">
        <%= image_tag "david.png", :class => "dev-img" %>
        <div class="dev-name">David Zhu</div>
      </div>
      <div class="col-md-1">
      </div>
    </div>
  </div>
</body>
</html>

app/views/parts/list.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RichCSS Parts</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "partials/header" %>

  <%= render partial: "partials/list" %>

  <%= render partial: "partials/footer" %>
</body>
</html>

app/views/parts/search.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RichCSS Parts</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
    <body>

    <%= render partial: "partials/header" %>

    <%= render partial: "partials/list" %>

    <%= render partial: "partials/footer" %>

    </body>
</html>

app/views/parts/show.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>RichCSS Parts</title>
	  <%= stylesheet_link_tag 'application' %>
	  <%= javascript_include_tag 'application' %>
	  <%= csrf_meta_tags %>
	</head>

  <body>
    <%= render partial: "partials/header" %>
		<div class="col-md-2"></div>

   	<div class="col-md-8">
      <div class="part-block">
        <h1 class="part-name-label"><%= @part[:name] %></h1> 
        <h3 class="version-label"><%= params[:version] ? params[:version] : @part[:version] %></h3>
      </div>

      <div class="part-desciption-block">
        <h4><i><%= @part[:description] %></i></h4>
      </div>

      <div class="sidebar">	
        <div class="sidebar-border"> 
          <div class="padding-bottom-15">
            <div class="total-downloads-header">TOTAL DOWNLOADS:</div> 
            <div class="total-downloads-label"><%= @part[:total_downloads] %></div>
          </div>

          <div class="padding-bottom-15">
            <div class="downloads-for-this-version-header">FOR THIS VERSION:</div> 
            <div class="downloads-for-this-version-label"><%= @downloads %></div>
          </div>

          <div class="links-header">LINKS:</div> 

          <div class="padding-bottom-5">
            <a class="links" href="<%= @downloadLink %>">
              Download
            </a>
          </div>
          <div>
            <a class="links" href="<%= @homepage %>">
              Homepage
            </a>
          </div>
        </div>
      </div>

      <div class="version-dependency-container">
        <div class="versions-block">
        	<div class="versions-label">VERSIONS:</div> 

          <% @versions.each do |version| %>
            <li class="bulletless-list"><a class="links" href="/parts/<%= @part[:name] %>/version/<%= version.version %>"><%= version.version %></a> <span class="color-C8C8C8">- <%= version.created_at.strftime("%b %d, %Y") %></span></li>
  			  <% end %>
  			</div>

        <% if !@dependencies.empty? %>
        <div class="dependencies-block">
          <div class="versions-label">DEPENDENCIES:</div> 

          <% @dependencies.each do |dependency| %>
            <li class="bulletless-list"><a class="links" href="/parts/<%= dependency.dependency_name %>"><%= dependency.dependency_name %></a> <span class="color-C8C8C8">- <%= dependency.dependency_version %></span></li>
          <% end %>
        </div>
        <% end %>
      </div>

      <div class="padding-top-bottom-30">
        <div class="authors-label">AUTHORS:</div> 
        <div><%= @part[:authors] %></div>
      </div>
    </div>

    <div class="col-md-2"></div>

    <%= render partial: "partials/footer" %>
  </body>
</html>